force-app/main/default/objects/Clock__c/Clock__c.object-meta.xml
<CustomObject>
    <label>Clock</label>
    <nameField>
        <displayFormat>clk-{0}</displayFormat>
        <label>Clock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clock__c/fields/show_24_Hour_Clock__c.field-meta.xml
<CustomField>
    <fullName>show_24_Hour_Clock__c</fullName>
    <defaultValue>false</defaultValue>
    <label>show 24 Hour Clock</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clock__c/fields/Time_Zone_Label__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone_Label__c</fullName>
    <label>Time Zone Label</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clock__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Clocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ClockController.cls
/*
 * @author: Gurjit Singh
 * @date: 19-May-2021
 * @group: Clock
 * @description: Apex controller for digitalClockContainer LWC page
 * @Test class: ClockControllerTest
 */
public without sharing class ClockController {

	/*******************************************************************
	   @description : Query the clock records associated with the logged in user.
	   @param   : NA
	   @return  : Array of clock records.
	 ********************************************************************/
	@AuraEnabled
	public static Clock__c[] getClocks(){

		Clock__c[] clocksArray  = new Clock__c[0];

		clocksArray = getClocksArray();

		if(clocksArray.isEmpty()) {
			Clock__c clock = createDefaultClock();
			clocksArray.add(clock);
		}

		return clocksArray;
	}

	/*******************************************************************
	   @description : Create a clock record with salesforce user's time zone and default label.
	   @param   : NA
	   @return  : Single clock record.
	 ********************************************************************/
	private static Clock__c createDefaultClock() {

		Clock__c clock = new Clock__c();
		clock.user__c  = UserInfo.getUserId();
		clock.show_24_Hour_Clock__c = false;
		clock.Time_Zone__c          = UserInfo.getTimeZone().getID();
		clock.Time_Zone_Label__c    = 'default';
		insert clock;
		return clock;
	}

	//query selector method on clock object.
	private static Clock__c[] getClocksArray() {
		return [SELECT Id, Name, show_24_Hour_Clock__c,Time_Zone__c, Time_Zone_Label__c,
		        User__c FROM Clock__c WHERE User__c =: UserInfo.getUserId() order by createdDate];
	}
}